export const UPDATE_POST_ID = 'UPDATE_POST_ID';
export const UPDATE_POST_TYPE = 'UPDATE_POST_TYPE';
export const UPDATE_GROUP_ID = 'UPDATE_GROUP_ID';
export const UPDATE_FILE_DATA = 'UPDATE_FILE_DATA';
export const UPDATE_DATA_FROM_FILE = 'UPDATE_DATA_FROM_FILE';
export const UPDATE_MAPPING = 'UPDATE_MAPPING';